name: "Build ARMv7 for Raspberry Pi (via Cross Docker Image)"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Tauri App for ARMv7
    runs-on: ubuntu-latest
    container:
      # نستخدم صورة جاهزة تدعم cross-compilation إلى armv7 مع musl
      image: messense/rust-musl-cross:armv7-musleabihf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build

      - name: Build Tauri App for ARMv7
        working-directory: src-tauri
        env:
          TAURI_ARCH: armv7
          TAURI_PLATFORM: linux
          TAURI_FAMILY: unix
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER: armv7-unknown-linux-musleabihf-gcc
          # هذا المتغير يخبر build scripts بعدم استخدام pkg-config للـ javascriptcoregtk-4.1
          JAVASCRIPTCOREGTK_4.1_NO_PKG_CONFIG: "1"
        run: |
          rustup target add armv7-unknown-linux-musleabihf
          cargo build --release --target armv7-unknown-linux-musleabihf

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-armv7-binary
          path: src-tauri/target/armv7-unknown-linux-musleabihf/release/*
