name: "Build ARMv7 (armhf) for Raspberry Pi Zero W2"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tauri-armhf:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust with ARM target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linux build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            pkg-config \
            gcc-arm-linux-gnueabihf \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libgtk-3-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            build-essential \
            curl \
            wget \
            file

      - name: Set up cross-compilation environment variables
        run: |
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Configure Cargo for cross-compilation
        run: |
          mkdir -p ~/.cargo
          echo '[target.armv7-unknown-linux-gnueabihf]' >> ~/.cargo/config.toml
          echo 'linker = "arm-linux-gnueabihf-gcc"' >> ~/.cargo/config.toml

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build

      - name: Build Tauri app for ARM
        run: cargo tauri build --target armv7-unknown-linux-gnueabihf

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: armhf-deb-package
          path: target/armv7-unknown-linux-gnueabihf/release/bundle/deb/*.deb
